In [2]:
import pandas as pd

In [39]:
df = pd.read_csv("ig_solar - Copy.csv",index_col=False)

In [40]:
df

,index,name,website,followers,last_post_likes,last_post_comments,last_post_date,Column1,dif_days,same_business_idea,reach_out
0,3,"Solar Energy Systems, LLC",http://www.solaresystems.com,4990.0,8.0,NaN,1 hour ago,7/23/2024,1,yes,yes
1,15,Orlando Solar Bears,http://www.orlandosolarbearshockey.com,51100.0,302.0,2.0,2 hour ago,7/23/2024,1,no,no
2,24,Sunrgy Solar Distribution,http://www.Sunrgy.com,2422.0,2.0,NaN,1 hour ago,7/23/2024,1,yes,yes
3,46,Solar-Ray Inc.,http://www.solar-ray.net,515.0,NaN,NaN,4 hour ago,7/23/2024,1,yes,yes
4,62,Elite Roofing and Solar,https://solarenergy.elite-roofs.com/,1255.0,2.0,NaN,6 hour ago,7/23/2024,1,yes,yes
...,...,...,...,...,...,...,...,...,...,...,...
62,152,P4 Solar,http://www.p4solar.com,2639.0,NaN,NaN,NaN,7/23/2024,45496,yes,no
63,176,SOLAR SOCCER CLUB,http://solarchelseafc.com,376.0,116.0,0.0,1 day ago,7/23/2024,1,no,no
64,179,Detach Reset Solar,https://detachresetsolar.com/,608.0,NaN,NaN,NaN,7/23/2024,45496,yes,no
65,199,LivSmart | LivSmart Solar,https://www.livsmartsolar.com/,57.0,NaN,NaN,NaN,7/23/2024,45496,no,no
66,208,SOLAR TITAN,http://www.solartitan.net,118.0,NaN,NaN,NaN,7/23/2024,45496,yes,no

In [41]:
df1 = pd.read_csv("ig_home_remodeling - Copy.csv")
df1

,index,name,website,followers,last_post_likes,last_post_comments,last_post_date,Column1,dif_days,same_business_idea,reach_out
0,63,"Monge Contracting Group, LLC",https://www.mongecontracting.com,63.0,4.0,NaN,23 minutes ago,7/23/2024,1,yes,yes
1,64,Design Lifestyles,http://www.designlifestyles.com,2204.0,5.0,NaN,6 hours ago,7/23/2024,1,yes,yes
2,67,Melde Construction Company,http://www.meldeconstruction.com,6382.0,NaN,1.0,5 hours ago,7/23/2024,1,yes,yes
3,85,Marwood Construction,https://www.marwoodconstruction.com/,271.0,NaN,1.0,11 hours ago,7/23/2024,1,yes,yes
4,86,CAM Construction,http://www.CamConstruction.net,1797.0,NaN,NaN,10 hours ago,7/23/2024,1,yes,yes
...,...,...,...,...,...,...,...,...,...,...,...
183,13,Nationwide Expos,https://www.nationwideexpos.com,12571.0,653.0,271.0,6/20/2024,7/23/2024,33,no,no
184,57,High Performance Homes,https://www.hphusa.com,23055.0,1476.0,565.0,5/24/2024,7/23/2024,60,yes,no
185,139,"Artemis Construction Management, LLC",http://artemis-cm.com,12161.0,709.0,316.0,5/23/2024,7/23/2024,61,yes,no
186,23,"Home Construction and Remodeling in San Jose, CA",https://dreamprinthomeremodeling.com/,8707.0,645.0,248.0,5/4/2024,7/23/2024,80,yes,no
187,135,CDS Contractors Inc,http://www.cdscontractors.com/,14252.0,1138.0,354.0,4/22/2024,7/23/2024,92,yes,no

In [42]:
df2 = pd.read_csv("ig_plumping - Copy.csv",index_col=False)
df2

,index,name,website,followers,last_post_likes,last_post_comments,last_post_date,Column1,dif_days,same_business_idea,reach_out
0,73,"A-Star Air Conditioning, Plumbing & Electric",http://www.astardfw.com/,247,NaN,NaN,7 hours ago,7/23/2024,1,no,no
1,74,"Blue Sky Plumbing, Heating, Cooling & Electric",http://www.blueskyplumbing.com,388,4.0,1.0,7 hours ago,7/23/2024,1,yes,yes
2,78,"Day & Night Air Conditioning, Heating and Plum...",http://www.DayandNightAir.com,709,3.0,1.0,5 hours ago,7/23/2024,1,no,no
3,90,"Heart Heating, Cooling, Plumbing & Electric",http://www.servicebyheart.us,175,1.0,1.0,9 hours ago,7/23/2024,1,no,no
4,94,Shadrach Plumbing & Cooling,https://shadrachplumbingcooling.com/,14,NaN,NaN,9 hours ago,7/23/2024,1,yes,yes
5,95,Option One Plumbing,http://www.optiononeplumbing.com,3318,19.0,NaN,2 hours ago,7/23/2024,1,yes,yes
6,108,"Robins Plumbing, Inc",http://www.robinsplumbing.com,662,NaN,NaN,3 hours ago,7/23/2024,1,yes,yes
7,124,Mike Counsil Plumbing,http://www.mcplumbing.com,198,1.0,NaN,4 hours ago,7/23/2024,1,yes,yes
8,20,Brothers Plumbing Heating and Electric,http://www.brothersplumbing.com/,133,1.0,NaN,2 days ago,7/23/2024,2,yes,yes
9,106,S & D Plumbing,http://www.sanddplumbing.com,732,3.0,NaN,3 days ago,7/23/2024,3,yes,yes
10,113,AAA AUGER Plumbing Services,http://www.aaa-auger.com,70,1.0,NaN,3 days ago,7/23/2024,3,no,no
11,89,Daniel's Plumbing and Air Conditioning,https://danielsaustin.com/,281,1.0,NaN,4 days ago,7/23/2024,4,no,no
12,101,Rooter Ranger Plumbing,http://www.rooterranger.com,4920,5.0,NaN,5 days ago,7/23/2024,5,no,no
13,8,BC Plumbing NV,https://bcplumbingnv.com,141,4.0,NaN,7 days ago,7/23/2024,7,yes,yes
14,46,Mountain Plumbing Products,https://mountainplumbing.com,484,4.0,NaN,7 days ago,7/23/2024,7,yes,yes
15,6,Applewood Plumbing Heating & Electric,http://www.ApplewoodFixIt.com,481,0.0,NaN,7/10/2024,7/23/2024,13,no,no
16,72,Nick's Plumbing Sewer & Air Conditioning,http://nicksplumbing.com,4063,3.0,NaN,7/10/2024,7/23/2024,13,yes,yes
17,5,Radiant Plumbing & Air Conditioning,http://www.CallRadiant.com,2088,27.0,1.0,5/17/2024,7/23/2024,67,no,no
18,80,Active Plumbing & Air Conditioning,https://activeplumbingandair.com,779,7.0,1.0,4/5/2024,7/23/2024,109,yes,yes
19,122,ASAP Plumbing Services,https://asapplumbingaz.com/,143,4.0,NaN,9/30/2023,7/23/2024,297,yes,yes
20,69,"Hawthorne Plumbing, Heating & Cooling",https://www.hawthornephc.com/,768,6.0,2.0,1/28/2023,7/23/2024,542,no,no
21,16,bluefrog Plumbing + DrainÂ® Headquarters,http://www.bluefrogfranchise.com/,123,12.0,2.0,4/21/2016,7/23/2024,3015,no,no
22,9,The Plumbing Agency,https://plumbingagency.com,51,NaN,NaN,NaN,7/23/2024,45496,no,no
23,25,NaN,http://theplumbinghouston.com,10,NaN,NaN,NaN,7/23/2024,45496,yes,no
24,31,"Paschal Air, Plumbing & Electric DFW",https://www.gopaschal.com,1438,NaN,NaN,NaN,7/23/2024,45496,no,no
25,40,"Peerless Plumbing Company, Inc",http://www.peerlessplumbingrepipes.com,244,NaN,NaN,NaN,7/23/2024,45496,yes,no
26,41,"Penguin Air, Plumbing & Electrical",https://www.penguinair.com/,1657,NaN,NaN,NaN,7/23/2024,45496,no,no
27,43,NaN,http://www.plumbingforless.co.uk/,1422,NaN,NaN,NaN,7/23/2024,45496,yes,no
28,65,NaN,http://plumbingtucson.com,11,NaN,NaN,NaN,7/23/2024,45496,no,no
29,85,Precision Air & Plumbing,https://www.precisionairandheating.com,565,NaN,NaN,NaN,7/23/2024,45496,no,no

In [43]:
final_df = pd.concat([df,df1,df2],axis=0,ignore_index=True)
final_df

,index,name,website,followers,last_post_likes,last_post_comments,last_post_date,Column1,dif_days,same_business_idea,reach_out
0,3,"Solar Energy Systems, LLC",http://www.solaresystems.com,4990.0,8.0,NaN,1 hour ago,7/23/2024,1,yes,yes
1,15,Orlando Solar Bears,http://www.orlandosolarbearshockey.com,51100.0,302.0,2.0,2 hour ago,7/23/2024,1,no,no
2,24,Sunrgy Solar Distribution,http://www.Sunrgy.com,2422.0,2.0,NaN,1 hour ago,7/23/2024,1,yes,yes
3,46,Solar-Ray Inc.,http://www.solar-ray.net,515.0,NaN,NaN,4 hour ago,7/23/2024,1,yes,yes
4,62,Elite Roofing and Solar,https://solarenergy.elite-roofs.com/,1255.0,2.0,NaN,6 hour ago,7/23/2024,1,yes,yes
...,...,...,...,...,...,...,...,...,...,...,...
280,40,"Peerless Plumbing Company, Inc",http://www.peerlessplumbingrepipes.com,244.0,NaN,NaN,NaN,7/23/2024,45496,yes,no
281,41,"Penguin Air, Plumbing & Electrical",https://www.penguinair.com/,1657.0,NaN,NaN,NaN,7/23/2024,45496,no,no
282,43,NaN,http://www.plumbingforless.co.uk/,1422.0,NaN,NaN,NaN,7/23/2024,45496,yes,no
283,65,NaN,http://plumbingtucson.com,11.0,NaN,NaN,NaN,7/23/2024,45496,no,no
284,85,Precision Air & Plumbing,https://www.precisionairandheating.com,565.0,NaN,NaN,NaN,7/23/2024,45496,no,no

In [44]:
final_df.fillna(0,inplace=True)
final_df

,index,name,website,followers,last_post_likes,last_post_comments,last_post_date,Column1,dif_days,same_business_idea,reach_out
0,3,"Solar Energy Systems, LLC",http://www.solaresystems.com,4990.0,8.0,0.0,1 hour ago,7/23/2024,1,yes,yes
1,15,Orlando Solar Bears,http://www.orlandosolarbearshockey.com,51100.0,302.0,2.0,2 hour ago,7/23/2024,1,no,no
2,24,Sunrgy Solar Distribution,http://www.Sunrgy.com,2422.0,2.0,0.0,1 hour ago,7/23/2024,1,yes,yes
3,46,Solar-Ray Inc.,http://www.solar-ray.net,515.0,0.0,0.0,4 hour ago,7/23/2024,1,yes,yes
4,62,Elite Roofing and Solar,https://solarenergy.elite-roofs.com/,1255.0,2.0,0.0,6 hour ago,7/23/2024,1,yes,yes
...,...,...,...,...,...,...,...,...,...,...,...
280,40,"Peerless Plumbing Company, Inc",http://www.peerlessplumbingrepipes.com,244.0,0.0,0.0,0,7/23/2024,45496,yes,no
281,41,"Penguin Air, Plumbing & Electrical",https://www.penguinair.com/,1657.0,0.0,0.0,0,7/23/2024,45496,no,no
282,43,0,http://www.plumbingforless.co.uk/,1422.0,0.0,0.0,0,7/23/2024,45496,yes,no
283,65,0,http://plumbingtucson.com,11.0,0.0,0.0,0,7/23/2024,45496,no,no
284,85,Precision Air & Plumbing,https://www.precisionairandheating.com,565.0,0.0,0.0,0,7/23/2024,45496,no,no

In [45]:
data = ['followers','last_post_likes','last_post_comments','dif_days',"same_business_idea"]

In [46]:
X = final_df[data]
y = final_df['reach_out']

In [47]:
X

,followers,last_post_likes,last_post_comments,dif_days,same_business_idea
0,4990.0,8.0,0.0,1,yes
1,51100.0,302.0,2.0,1,no
2,2422.0,2.0,0.0,1,yes
3,515.0,0.0,0.0,1,yes
4,1255.0,2.0,0.0,1,yes
...,...,...,...,...,...
280,244.0,0.0,0.0,45496,yes
281,1657.0,0.0,0.0,45496,no
282,1422.0,0.0,0.0,45496,yes
283,11.0,0.0,0.0,45496,no
284,565.0,0.0,0.0,45496,no

In [48]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
X['same_business_idea'] = lb.fit_transform(X["same_business_idea"])
X

C:\Users\dell\AppData\Local\Temp\ipykernel_12544\4074352565.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['same_business_idea'] = lb.fit_transform(X["same_business_idea"])

,followers,last_post_likes,last_post_comments,dif_days,same_business_idea
0,4990.0,8.0,0.0,1,1
1,51100.0,302.0,2.0,1,0
2,2422.0,2.0,0.0,1,1
3,515.0,0.0,0.0,1,1
4,1255.0,2.0,0.0,1,1
...,...,...,...,...,...
280,244.0,0.0,0.0,45496,1
281,1657.0,0.0,0.0,45496,0
282,1422.0,0.0,0.0,45496,1
283,11.0,0.0,0.0,45496,0
284,565.0,0.0,0.0,45496,0

In [49]:
y = lb.fit_transform(y)
y = y.ravel()
y

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [50]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,stratify=X["same_business_idea"],test_size=0.2,random_state=42)

In [51]:
from imblearn.over_sampling import SMOTE
from collections import Counter

smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

# Check the class distribution before and after SMOTE
print("Original class distribution:", Counter(y_train))
print("Resampled class distribution:", Counter(y_train_res))

Original class distribution: Counter({0: 174, 1: 54})
Resampled class distribution: Counter({1: 174, 0: 174})

In [68]:
from sklearn.ensemble import RandomForestClassifier 

rdtc = RandomForestClassifier(max_depth=3,random_state=42,oob_score=True,criterion='entropy')
rdtc.fit(X_train_res,y_train_res)

RandomForestClassifier(criterion='entropy', max_depth=3, oob_score=True,
                       random_state=42)

In [69]:
rdtc.score(X_train_res,y_train_res)

0.985632183908046

In [70]:
rdtc.oob_score_

0.9712643678160919

In [71]:
from sklearn.metrics import precision_score , recall_score

y_pred = rdtc.predict(X_train_res)

print(precision_score(y_train_res,y_pred))
print(recall_score(y_train_res,y_pred))

0.9884393063583815
0.9827586206896551

In [73]:
y_pred = rdtc.predict(X_test)

print(precision_score(y_test,y_pred))
print(recall_score(y_test,y_pred))

0.8
1.0

In [74]:
rdtc.score(X_test,y_test)

0.9649122807017544

In [214]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=42)
ada= AdaBoostClassifier(dtc,random_state=42)

In [215]:
from sklearn.model_selection import GridSearchCV
# Define the base estimator
dtc = DecisionTreeClassifier(random_state=42)

# Define the parameter grid
param_grid = {
    'base_estimator__max_leaf_nodes': [2,4,6],
    'base_estimator__max_depth': [2, 3, 4],
    'base_estimator__splitter': ['best', 'random'],
    'base_estimator__min_samples_leaf': [1, 5, 10],
    'base_estimator__min_samples_split': [2, 10, 20],
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 1]
}

In [216]:
grid_search = GridSearchCV(estimator=ada, param_grid=param_grid, cv=3, n_jobs=-1, scoring='precision')

In [217]:
grid_search.fit(X_train_res,y_train_res)

c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:930: FutureWarning: Parameter 'base_estimator' of AdaBoostClassifier is deprecated in favor of 'estimator'. See AdaBoostClassifier's docstring for more details.
  self.best_estimator_ = clone(base_estimator).set_params(

GridSearchCV(cv=3,
             estimator=AdaBoostClassifier(estimator=DecisionTreeClassifier(random_state=42),
                                          random_state=42),
             n_jobs=-1,
             param_grid={'base_estimator__max_depth': [2, 3, 4],
                         'base_estimator__max_leaf_nodes': [2, 4, 6],
                         'base_estimator__min_samples_leaf': [1, 5, 10],
                         'base_estimator__min_samples_split': [2, 10, 20],
                         'base_estimator__splitter': ['best', 'random'],
                         'learning_rate': [0.01, 0.1, 1],
                         'n_estimators': [50, 100, 200]},
             scoring='precision')

In [218]:
best_params = grid_search.best_params_
best_estimator = grid_search.best_estimator_
best_score = grid_search.best_score_

print("Best Parameters:", best_params)
print("Best Estimator:", best_estimator)
print("Best Score:", best_score)

Best Parameters: {'base_estimator__max_depth': 3, 'base_estimator__max_leaf_nodes': 6, 'base_estimator__min_samples_leaf': 1, 'base_estimator__min_samples_split': 20, 'base_estimator__splitter': 'best', 'learning_rate': 0.01, 'n_estimators': 50}
Best Estimator: AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=3,
                                                    max_leaf_nodes=6,
                                                    min_samples_split=20,
                                                    random_state=42),
                   learning_rate=0.01, random_state=42)
Best Score: 0.9884049203468441

In [219]:
from sklearn.model_selection import cross_val_score
# Assume X and y are your features and target data
scores = cross_val_score(grid_search.best_estimator_, X_train_res, y_train_res, cv=4, scoring='precision')

In [220]:
print(f"Cross-validated scores: {scores}")
print(f"Mean cross-validated score: {scores.mean()}")
print(f"Standard deviation of cross-validated scores: {scores.std()}")

Cross-validated scores: [1.         0.97727273 0.97674419 1.        ]
Mean cross-validated score: 0.9885042283298098
Standard deviation of cross-validated scores: 0.01149729036650052

In [221]:
y_pred = grid_search.best_estimator_.predict(X_train_res)

print(precision_score(y_train_res,y_pred))
print(recall_score(y_train_res,y_pred))

1.0
1.0

In [222]:
grid_search.best_estimator_.score(X_train_res,y_train_res)

1.0

In [223]:
grid_search.best_estimator_.score(X_test,y_test)

1.0

In [224]:
y_pred = grid_search.best_estimator_.predict(X_test)

print(precision_score(y_test,y_pred))
print(recall_score(y_test,y_pred))

1.0
1.0

In [225]:
grid_search.best_estimator_.predict([[10332,102,80,65,1]])

c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

array([0])